// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBd3ysHqQdQ7DuZkBc7IrucLYSWGpzGU',
    appId: '1:271622300760:web:b1bc1ba2e100b106e4562d',
    messagingSenderId: '271622300760',
    projectId: 'storefront-b0d60',
    authDomain: 'storefront-b0d60.firebaseapp.com',
    storageBucket: 'storefront-b0d60.appspot.com',
    measurementId: 'G-4NG5PBPK33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnllKrTiJkyvzJ3jobmrijl07aTRDa6HA',
    appId: '1:271622300760:android:e880aa760ecece2de4562d',
    messagingSenderId: '271622300760',
    projectId: 'storefront-b0d60',
    storageBucket: 'storefront-b0d60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCirDGfSytOQn7tryqeAMb3Z_Z89Pnbyvo',
    appId: '1:271622300760:ios:ce2cddeeafd741e4e4562d',
    messagingSenderId: '271622300760',
    projectId: 'storefront-b0d60',
    storageBucket: 'storefront-b0d60.appspot.com',
    iosBundleId: 'com.example.storefront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCirDGfSytOQn7tryqeAMb3Z_Z89Pnbyvo',
    appId: '1:271622300760:ios:1bffec70503a5ce3e4562d',
    messagingSenderId: '271622300760',
    projectId: 'storefront-b0d60',
    storageBucket: 'storefront-b0d60.appspot.com',
    iosBundleId: 'com.example.storefront.RunnerTests',
  );
}
